project_id = "xzxjwuzwltoapifcyzww"

[functions.auth-2fa]
verify_jwt = true

[functions.device-activate]
verify_jwt = true

[functions.identity-verify]
verify_jwt = true

[functions.location-verify]
verify_jwt = true

[functions.youtube-upload]
verify_jwt = true
