
project_id = "xzxjwuzwltoapifcyzww"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322

[studio]
enabled = true
port = 54323

[functions.device-registration]
verify_jwt = false

[functions.provision-nextdns]
verify_jwt = false

[functions.ensure-child-profiles]
verify_jwt = true

[functions.nextdns-anonymize]
verify_jwt = true

[functions.nextdns-analytics]
verify_jwt = true

[functions.activation-status]
verify_jwt = false

[functions.device-config]
verify_jwt = false

[functions.heartbeat]
verify_jwt = false

[functions.nova-verify-child]
verify_jwt = false

[functions.nova-verify-child-token]
verify_jwt = false

[functions.nova-start-session]
verify_jwt = true

[functions.nova-start-session-token]
verify_jwt = false

[functions.nova-end-session]
verify_jwt = true

[functions.nova-end-session-token]
verify_jwt = false

[functions.nova-update-progress-token]
verify_jwt = false

[functions.nova-chunk]
verify_jwt = true

[functions.nova-mint-child-token]
verify_jwt = true

[functions.nova-generate-insights]
verify_jwt = false

[functions.nova-job-worker]
verify_jwt = false

[functions.nova-illustrations-ensure-slot2]
verify_jwt = true

[functions.text-to-speech]
verify_jwt = false

[functions.books-batch-reingest]
verify_jwt = true

[functions.tts-analyze]
verify_jwt = true

[functions.tts-render]
verify_jwt = true

[functions.book-ingest]
verify_jwt = false

[functions.admin-books-reingest]
verify_jwt = true

[functions.get-book-pages]
verify_jwt = false

[functions.nova-realtime-chat]
verify_jwt = false

[functions.realtime-chat]
verify_jwt = false

[functions.device-heartbeat]
verify_jwt = false

[functions.device-app-manifest]
verify_jwt = false

[functions.device-postinstall]
verify_jwt = false

[functions.device-jobs-poll]
verify_jwt = false

[functions.device-status]
verify_jwt = false

[functions.livestream-feedback]
verify_jwt = false

[functions.device-app-inventory]
verify_jwt = false

[functions.device-app-usage]
verify_jwt = false

[functions.demo-ingest]
verify_jwt = false