
project_id = "xzxjwuzwltoapifcyzww"

[functions.auth-2fa]
verify_jwt = true

[functions.device-activate]
verify_jwt = true

[functions.identity-verify]
verify_jwt = true

[functions.location-verify]
verify_jwt = true

[functions.youtube-upload]
verify_jwt = true

# New: bind-device requires parent JWT
[functions.bind-device]
verify_jwt = true

# New: device-status is public (device polls without auth)
[functions.device-status]
verify_jwt = false

