
project_id = "xzxjwuzwltoapifcyzww"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322

[studio]
enabled = true
port = 54323

[functions.nova-verify-child]
verify_jwt = false

[functions.nova-start-session]
verify_jwt = true

[functions.nova-end-session]
verify_jwt = true

[functions.nova-chunk]
verify_jwt = true

[functions.nova-mint-child-token]
verify_jwt = true

[functions.nova-generate-insights]
verify_jwt = false

[functions.nova-job-worker]
verify_jwt = false

[functions.nova-illustrations-ensure-slot2]
verify_jwt = true

[functions.text-to-speech]
verify_jwt = false

[functions.books-batch-reingest]
verify_jwt = true

[functions.tts-analyze]
verify_jwt = true

[functions.tts-render]
verify_jwt = true

[functions.book-ingest]
verify_jwt = false

[functions.admin-books-reingest]
verify_jwt = true

[functions.get-book-pages]
verify_jwt = false
