
project_id = "xzxjwuzwltoapifcyzww"

[functions.auth-2fa]
verify_jwt = true

[functions.device-activate]
verify_jwt = true

[functions.identity-verify]
verify_jwt = true

[functions.location-verify]
verify_jwt = true

[functions.youtube-upload]
verify_jwt = true

# Existing: bind-device requires parent JWT
[functions.bind-device]
verify_jwt = true

# Existing: device-status is public (device polls without auth)
[functions.device-status]
verify_jwt = false

# New: device-config (device_jwt; we verify manually)
[functions.device-config]
verify_jwt = false

# New: device-heartbeat (device_jwt; we verify manually)
[functions.device-heartbeat]
verify_jwt = false

# New: device-app-manifest (device_jwt; we verify manually)
[functions.device-app-manifest]
verify_jwt = false

# New: device-refresh (device_jwt; we verify manually)
[functions.device-refresh]
verify_jwt = false

# New: rotate-device-token (parent-auth required)
[functions.rotate-device-token]
verify_jwt = true

# New: stripe-webhook (public endpoint from Stripe; we verify signature)
[functions.stripe-webhook]
verify_jwt = false

# Admin functions (parent/admin auth required)
[functions.device-config-admin]
verify_jwt = true

[functions.admin-list-devices]
verify_jwt = true

# NextDNS profile management (parent auth required)
[functions.nextdns-profile-manager]
verify_jwt = true
